export const MOCK_DATA = {
    header: {
        links: [
            { label: "LIT ZONE", href: "/lit-zone" },
            { label: "ZECODE NEAR YOU", href: "/store-locator" },
            { label: "ABOUT", href: "/about" },
            { label: "MEN", href: "/men" },
            { label: "WOMEN", href: "/women" },
            { label: "KIDS", href: "/kids" },
        ],
    },
    hero: {
        title: "YOUR NEW FASHION CODE",
        subtitle: "Urban Clothing Stores in India",
        image: "/hero/hero1.png",
        cta: "FIND YOUR CODE",
    },
    categories: [
        {
            id: 1,
            title: "MEN",
            image: "/categories/men.png",
            link: "/men",
            subcategories: [
                {
                    id: 11,
                    title: "T-SHIRTS",
                    image: "/categories/men-tshirts.png",
                    link: "/men/tshirts",
                },
                {
                    id: 12,
                    title: "SHIRTS",
                    image: "/categories/men-shirts.png",
                    link: "/men/shirts",
                },
                {
                    id: 13,
                    title: "JEANS",
                    image: "/categories/men-jeans.png",
                    link: "/men/jeans",
                },
                {
                    id: 14,
                    title: "TROUSERS",
                    image: "/categories/men-trousers.png",
                    link: "/men/trousers",
                },
                {
                    id: 15,
                    title: "JACKETS",
                    image: "/categories/men-jackets.png",
                    link: "/men/jackets",
                },
                {
                    id: 16,
                    title: "SHOES",
                    image: "/categories/men-shoes.png",
                    link: "/men/shoes",
                },
            ],
        },
        {
            id: 2,
            title: "WOMEN",
            image: "/categories/women.png",
            link: "/women",
            subcategories: [
                {
                    id: 21,
                    title: "TOPS",
                    image: "/categories/women-tops.png",
                    link: "/women/tops",
                },
                {
                    id: 22,
                    title: "DRESSES",
                    image: "/categories/women-dresses.png",
                    link: "/women/dresses",
                },
                {
                    id: 23,
                    title: "JEANS",
                    image: "/categories/women-jeans.png",
                    link: "/women/jeans",
                },
                {
                    id: 24,
                    title: "SKIRTS",
                    image: "/categories/women-skirts.png",
                    link: "/women/skirts",
                },
                {
                    id: 25,
                    title: "JACKETS",
                    image: "/categories/women-jackets.png",
                    link: "/women/jackets",
                },
                {
                    id: 26,
                    title: "SHOES",
                    image: "/categories/women-shoes.png",
                    link: "/women/shoes",
                },
            ],
        },
        {
            id: 3,
            title: "KIDS",
            image: "/categories/kids.png",
            link: "/kids",
            subcategories: [
                {
                    id: 31,
                    title: "BOYS T-SHIRTS",
                    image: "/categories/kids-boys-tshirts.png",
                    link: "/kids/boys-tshirts",
                },
                {
                    id: 32,
                    title: "GIRLS TOPS",
                    image: "/categories/kids-girls-tops.png",
                    link: "/kids/girls-tops",
                },
                {
                    id: 33,
                    title: "BOYS JEANS",
                    image: "/categories/kids-boys-jeans.png",
                    link: "/kids/boys-jeans",
                },
                {
                    id: 34,
                    title: "GIRLS DRESSES",
                    image: "/categories/kids-girls-dresses.png",
                    link: "/kids/girls-dresses",
                },
                {
                    id: 35,
                    title: "JACKETS",
                    image: "/categories/kids-jackets.png",
                    link: "/kids/jackets",
                },
                {
                    id: 36,
                    title: "SHOES",
                    image: "/categories/kids-shoes.png",
                    link: "/kids/shoes",
                },
            ],
        },
    ],
    footer: {
        links: [
            { label: "About Us", href: "/about" },
            { label: "Store Locator", href: "/store-locator" },
        ],
    },
    products: [
        {
            id: 101,
            name: "Urban Oversized Tee",
            slug: "urban-oversized-tee",
            category: "men",
            categoryLabel: "T-Shirts",
            price: 1299,
            originalPrice: 1599,
            image: "/products/men-tee.png",
            gallery: [
                "/products/men-tee.png",
                "/placeholders/thumb-default.jpg",
                "/placeholders/thumb-default.jpg",
                "/placeholders/thumb-default.jpg",
            ],
            description: "Crafted for the modern urbanite, this oversized tee features premium cotton fabric and a relaxed fit. Perfect for street style looks.",
            sizes: ["S", "M", "L", "XL"],
            rating: 4.6,
            reviewCount: 124,
        },
        {
            id: 102,
            name: "Slim Fit Chinos",
            slug: "slim-fit-chinos",
            category: "men",
            categoryLabel: "Bottoms",
            price: 1999,
            originalPrice: 2399,
            image: "/products/men-chinos.jpg",
            gallery: [
                "/products/men-chinos.jpg",
                "/placeholders/thumb-default.jpg",
                "/placeholders/thumb-default.jpg",
                "/placeholders/thumb-default.jpg",
            ],
            description: "Versatile slim fit chinos that transition seamlessly from work to weekend. Made with stretch cotton for all-day comfort.",
            sizes: ["30", "32", "34", "36"],
            rating: 4.4,
            reviewCount: 98,
        },
        {
            id: 201,
            name: "Floral Summer Dress",
            slug: "floral-summer-dress",
            category: "women",
            categoryLabel: "Dresses",
            price: 2499,
            originalPrice: 2999,
            image: "/products/women-dress.jpg",
            gallery: [
                "/products/women-dress.jpg",
                "/placeholders/thumb-default.jpg",
                "/placeholders/thumb-default.jpg",
                "/placeholders/thumb-default.jpg",
            ],
            description: "Embrace the season with this breezy floral dress. Features a flattering waistline and lightweight fabric.",
            sizes: ["XS", "S", "M", "L"],
            rating: 4.8,
            reviewCount: 176,
        },
        {
            id: 202,
            name: "Denim Jacket",
            slug: "denim-jacket",
            category: "women",
            categoryLabel: "Outerwear",
            price: 2999,
            originalPrice: 3499,
            image: "/products/women-jacket.jpg",
            gallery: [
                "/products/women-jacket.jpg",
                "/placeholders/thumb-default.jpg",
                "/placeholders/thumb-default.jpg",
                "/placeholders/thumb-default.jpg",
            ],
            description: "A classic denim jacket with a modern twist. Distressed details and a cropped fit make it a wardrobe essential.",
            sizes: ["S", "M", "L"],
            rating: 4.5,
            reviewCount: 142,
        },
        {
            id: 301,
            name: "Kids Graphic Tee",
            slug: "kids-graphic-tee",
            category: "kids",
            categoryLabel: "T-Shirts",
            price: 799,
            originalPrice: 999,
            image: "/placeholders/thumb-default.jpg",
            gallery: [
                "/placeholders/thumb-default.jpg",
                "/placeholders/thumb-default.jpg",
                "/placeholders/thumb-default.jpg",
                "/placeholders/thumb-default.jpg",
            ],
            description: "Fun and playful graphic tee for the little ones. Soft, durable fabric that stands up to playtime.",
            sizes: ["4-5Y", "6-7Y", "8-9Y"],
            rating: 4.7,
            reviewCount: 63,
        },
        {
            id: 302,
            name: "Comfort Joggers",
            slug: "comfort-joggers",
            category: "kids",
            categoryLabel: "Bottoms",
            price: 999,
            originalPrice: 1199,
            image: "/placeholders/thumb-default.jpg",
            gallery: [
                "/placeholders/thumb-default.jpg",
                "/placeholders/thumb-default.jpg",
                "/placeholders/thumb-default.jpg",
                "/placeholders/thumb-default.jpg",
            ],
            description: "Super soft joggers for active kids. Elastic waistband and ribbed cuffs ensure a perfect fit.",
            sizes: ["4-5Y", "6-7Y", "8-9Y"],
            rating: 4.5,
            reviewCount: 58,
        },
    ],
};
