export const MOCK_DATA = {
    header: {
        links: [
            { label: "LIT ZONE", href: "/lit-zone" },
            { label: "ZECODE NEAR YOU", href: "/store-locator" },
            { label: "ABOUT", href: "/about" },
            { label: "MEN", href: "/men" },
            { label: "WOMEN", href: "/women" },
            { label: "KIDS", href: "/kids" },
        ],
    },
    hero: {
        title: "YOUR NEW FASHION CODE",
        subtitle: "Urban Clothing Stores in India",
        image: "/hero-bg.jpg",
        cta: "FIND YOUR CODE",
    },
    categories: [
        {
            id: 1,
            title: "MEN",
            image: "/categories/men.jpg",
            link: "/men",
        },
        {
            id: 2,
            title: "WOMEN",
            image: "/categories/women.jpg",
            link: "/women",
        },
        {
            id: 3,
            title: "KIDS",
            image: "/categories/kids.jpg",
            link: "/kids",
        },
    ],
    footer: {
        links: [
            { label: "About Us", href: "/about" },
            { label: "Store Locator", href: "/store-locator" },
        ],
    },
    products: [
        {
            id: 101,
            name: "Urban Oversized Tee",
            category: "men",
            price: 1299,
            image: "/products/men-tee.jpg",
            description: "Crafted for the modern urbanite, this oversized tee features premium cotton fabric and a relaxed fit. Perfect for street style looks.",
            sizes: ["S", "M", "L", "XL"],
        },
        {
            id: 102,
            name: "Slim Fit Chinos",
            category: "men",
            price: 1999,
            image: "/products/men-chinos.jpg",
            description: "Versatile slim fit chinos that transition seamlessly from work to weekend. Made with stretch cotton for all-day comfort.",
            sizes: ["30", "32", "34", "36"],
        },
        {
            id: 201,
            name: "Floral Summer Dress",
            category: "women",
            price: 2499,
            image: "/products/women-dress.jpg",
            description: "Embrace the season with this breezy floral dress. Features a flattering waistline and lightweight fabric.",
            sizes: ["XS", "S", "M", "L"],
        },
        {
            id: 202,
            name: "Denim Jacket",
            category: "women",
            price: 2999,
            image: "/products/women-jacket.jpg",
            description: "A classic denim jacket with a modern twist. Distressed details and a cropped fit make it a wardrobe essential.",
            sizes: ["S", "M", "L"],
        },
        {
            id: 301,
            name: "Kids Graphic Tee",
            category: "kids",
            price: 799,
            image: "/products/kids-tee.jpg",
            description: "Fun and playful graphic tee for the little ones. Soft, durable fabric that stands up to playtime.",
            sizes: ["4-5Y", "6-7Y", "8-9Y"],
        },
        {
            id: 302,
            name: "Comfort Joggers",
            category: "kids",
            price: 999,
            image: "/products/kids-joggers.jpg",
            description: "Super soft joggers for active kids. Elastic waistband and ribbed cuffs ensure a perfect fit.",
            sizes: ["4-5Y", "6-7Y", "8-9Y"],
        },
    ],
};
